name: main

on:
  push:
    branches:
      - main

env:
  IMAGE_REPOSITORY: hiddendev/gh-actions-demo

jobs:
  version:
    name: "Release"
    environment: Docker Hub
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install python-semantic-release
        run: pip install python-semantic-release
      - name: Generate version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: set-version
        run: |
          semantic-release version --skip-build --no-commit
          echo "VERSION=$(semantic-release version --print)" >> $GITHUB_ENV

      - uses: astral-sh/setup-uv@v5

      - name: Update uv.lock with new version
        run: |
          uv sync
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add uv.lock pyproject.toml
          git commit -m "chore(release): release v${{ env.VERSION }}"
          git push
          git push --tags

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:${{ env.VERSION }}